### ISSUE TITLE
Подключить авторизацию на все веб-страницы проекта

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#129]

**Comment by npatyur** [comment]
pull request:
https://github.com/OSLL/mooc-lp-statistics/pull/157

**Comment by zmm** [comment]
Для selenium тестов нужно сделать новый тест, который будет авторизоваться через форму логина и после этого должны запускаться остальные тесты.

**Comment by zmm** [comment]
После деплоя происходит вот такое
```
AttributeError at /
'WSGIRequest' object has no attribute 'user'
Request Method:	GET
Request URL:	http://mooc-lp-statistics/
Django Version:	1.9.4
Exception Type:	AttributeError
Exception Value:	
'WSGIRequest' object has no attribute 'user'
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py in _wrapped_view, line 22
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/var/www/mooc-lp-statistics/WebApp',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/PIL',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gst-0.10',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-client',
 '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel',
 '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol',
 '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode',
 '/var/www/mooc-lp-statistics/',
 '/var/www/mooc-lp-statistics/App/',
 '/var/www/mooc-lp-statistics/WebApp/']
```

**Comment by zmm** [comment]
+  в процессе деплоя 
```
vood@vood-ThinkPad:~/ws/mooc-lp-statistics$ sudo ./scripts/local_deploy.sh 
./scripts/local_deploy.sh: строка 7: DJANGO_USER_NAME: команда не найдена
Enter username for django superuser
```
+ процедура создания пользователя достаточно сложная и не совсем понятно, как ее автоматически запускать в интерактивном режиме. Может быть лучше принимать имя пользователя/ пароль в качестве аргументов local_deploy.sh, а если они не заданы - делать их рандомными и печатать в командную строку?

**Comment by zmm** [comment]
В процессе установки получил вот такую ошибку, хотя у меня все зависимости из requirements установлены.
```
vood@vood-ThinkPad:~/ws/mooc-lp-statistics$ sudo ./scripts/local_deploy.sh 
Requirement already satisfied (use --upgrade to upgrade): pymongo==3.4 in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): django in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): mongoengine in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): selenium in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): webapp2 in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): webob in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): djangorestframework in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): pyparsing in /usr/local/lib/python2.7/dist-packages (from -r scripts/requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from webapp2->-r scripts/requirements.txt (line 5))
Cleaning up...
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Generated PASSWORD MzNkODE2NmI3N2JmNjc0MjU1ODU3OWQy
Operations to perform:
  Apply all migrations: admin, contenttypes, auth, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/var/www/mooc-lp-statistics/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.createadminuser
Site mooc-lp-statistics already enabled
 * Restarting web server apache2                                                                                                        AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
```
